### ISSUE TITLE
Input Manager Version 1.1

### ISSUE THREAD

**Issue by GoofyCoderGuy** [FRC9015/Crescendo#16]
Update Input Manager to let commands be mapped to the triggers and have a command be called continuously while a button is held down because Raunak complained too much.

**Comment by lazychino** [comment]
Suggestion/Reminder: The `InputManager` should be an abstraction layer so that you can use multiple controllers without refactoring other code. Please don't go overboard adding extra stuff not support by default controllers.

With that said, can you expand on what mean support for triggers and holding buttons?

Probably this can be broken in to multiple issues that can be handle separately. +1 to operator controller this is required
